export interface inquiry
{
  DOC_NUMBER:'DOC_NUMBER',
  OPER:'OPERATION',
  REC_DATE:'REC_DATE',
  REC_TIME:'REC_TIME',
  CREATED_BY:'CREATED_BY',
  DOC_DATE:'DOC_DATE',
  TRAN_GROUP:'TRAN_GROUP',
  DOC_TYPE:'DOC_TYPE',
  NET_VAL:'NET_VAL_HD',
  CURRENCY:'CURRENCY',
  SALES_ORG:'SALES_ORG'
}
